import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  '/base/': [
    '/base/kongyiji.md',
    '/base/mutinyAndInvolution.md',
    '/base/xijin1.md',
    '/base/xijin2.md',
    '/base/xijin3.md',
    '/base/chernobyl.md',
    '/base/ancientNames.md',
  ],
  '/jinji/': [
    '/jinji/1.md',
    '/jinji/2.md',
    '/jinji/3.md',
    '/jinji/4.md',
    '/jinji/5.md',
    '/jinji/6.md',
    '/jinji/7.md',
    '/jinji/8.md',
    '/jinji/9.md',
    '/jinji/10.md',
    '/jinji/11.md',
    '/jinji/12.md',
    '/jinji/13.md',
    '/jinji/14.md',
    '/jinji/15.md',
    '/jinji/16.md',
    '/jinji/17.md',
    '/jinji/18.md',
    '/jinji/19.md',
    '/jinji/20.md',
    '/jinji/21.md',
    '/jinji/22.md',
  ],
  '/scaryGhostStory/': [
    '/scaryGhostStory/1.md',
  ],
});